translator_task:
    description: >
        Translate {sentence} from English to Korean without making mistakes
    expected_output: >
        A well formatted translation from English to Korean using proper capitalization of names and places.
    agent: translator_agent

retranslator_task:
    description: >
        Translate {sentence} from Korean to French without making mistakes
    expected_output: >
        A well formatted translation from Korean to French using proper capitalization of names and places.
    agent: translator_agent