job_extraction_task:
  description: >
    {location}에서 {level} 레벨 {position} 채용 공고를 찾아 추출합니다.

    단계:
    1. 웹 검색 도구를 사용해 {location}의 {level} 레벨 {position} 채용 공고를 검색합니다.
    2. 검색 결과에서 채용 공고를 추출합니다.
    3. {location}의 {level} 레벨 {position}가 아닌 공고를 필터링합니다.
  expected_output: >
    `JobList` 스키마와 일치하는 JSON 객체.
  agent: job_search_agent

job_matching_task:
  description: >
    당신은 커리어 매칭 전문가입니다.

    추출된 채용 공고 목록(JobList)과 사용자의 이력서를 바탕으로 각 공고가 사용자와 얼마나 잘 맞는지 아래 기준으로 평가하세요:
    - 기술 스택
    - 역할 레벨
    - 산업 및 기업 규모 선호도
    - 원격/근무 유연성
    - 고용 형태(정규/계약 등)
    - 연봉 기대치
    - 이력서에 있는 키워드와 감점 요인

    각 공고에 대해 `match_score`를 1(부적합)에서 5(완전 적합)까지 부여하고, 그 근거를 설명하세요.

    목록의 각 공고에 `match_score`와 `reason` 필드를 추가하세요.

    원본 공고의 모든 필드는 그대로 유지하고, 어떤 공고도 수정하거나 제거하지 마세요.
  expected_output: >
    원본 `JobList` 스키마와 일치하되, 각 공고에 다음 두 필드가 추가된 JSON 객체:
    - match_score: 1~5 사이의 정수
    - reason: 점수에 대한 짧은 설명
  agent: job_matching_agent

job_selection_task:
  description: >
    당신은 직무 선택 전문가입니다.

    `match_score`와 `reason` 필드를 가진 공고 목록(RankedJobList)이 주어졌을 때, 다음을 수행하세요:
    1. `match_score`와 사유를 분석해 사용자에게 가장 잘 맞는 단 하나의 공고를 선정합니다.
    2. 사용자의 선호, 기술, 목표에 가장 근접하게 부합하는 최상위 공고를 선택합니다.
    3. 이력서-공고 정렬을 근거로 간결한 `reason`을 제시합니다.
    4. 최상위 공고의 `selected`를 `true`로, 나머지는 `false`로 설정합니다.

    원본 공고 필드(예: job_title, company_name 등)의 내용은 변경하지 마세요.
  expected_output: >
    선택된 공고의 `ChosenJob` 스키마와 일치하는 JSON 객체.
  agent: job_matching_agent

resume_rewriting_task:
  description: >
    당신은 이력서 최적화 전문가입니다.

    포함된 지식 소스로 제공되는 사용자의 실제 이력서와 선택된 공고(ChosenJob)를 바탕으로, **기존 이력서를 재작성**하여
    **직무 정렬을 강조**하되, 어떤 사실도 **허위로 추가하거나 과장하지 마세요**.

    중점 사항:
    - 관련 기술, 프로젝트, 성과를 재배치·재서술·강조
    - 요약과 경력 항목을 핵심 요구사항과 키워드에 맞게 재작성
    - 공고의 톤, 기술 초점, 용어와 일치
    - 사용자의 원래 이력서에 있는 실제 경험만 유지

    관련 없는 내용은 제거하거나 제목을 약간 다듬을 수 있지만, **가짜 회사, 기술, 날짜, 역할을 추가해서는 안 됩니다**.

  expected_output: >
    선택된 공고에 맞춰 재작성·최적화된, **실제 사용자의 이력서**의 Markdown 형식 버전.
    이력서는 사용자의 실제 이력에 근거하여 진실성을 유지해야 합니다.

  agent: resume_optimization_agent
  output_file: output/rewritten_resume.md
  create_directory: true
  markdown: true

company_research_task:
  description: >
    당신은 기업 리서치 및 면접 준비 전문가입니다.

    선택된 공고(ChosenJob)를 기준으로 공개 웹 자원을 활용해 채용 기업을 조사하세요.
    목표:
    1. 기업 규모, 산업, 미션, 가치, 최근 소식 파악
    2. 공고를 분석해 팀 구조와 제품 맥락 추론
    3. 후보자가 마주할 수 있는 잠재적 면접 주제와 질문 제안
    4. 면접에서 물어볼 수 있는 인사이트 있는 질문 목록 제공

    기업 웹사이트, 보도자료, 블로그, 소셜 미디어, 리뷰를 활용해 인사이트를 수집하세요.
  expected_output: >
    다음 섹션을 포함한 Markdown 파일:
    - ## 회사 개요
    - ## 미션과 가치
    - ## 최근 뉴스 또는 변화
    - ## 역할 맥락과 제품 관여도
    - ## 예상 면접 주제
    - ## 면접에서 물어볼 질문

  agent: company_research_agent
  markdown: true
  output_file: output/company_research.md

interview_prep_task:
  description: >
    당신은 면접 준비 코치입니다.

    다음 정보를 통합하세요:
    1. 선택된 공고(ChosenJob)
    2. 맞춤 이력서(RewrittenResume)
    3. 기업 리서치 요약(CompanyResearch)

    다음을 포함한 상세 면접 준비 문서를 작성하세요:
    - 직무에 대한 간단한 요약과 후보자에게 적합한 이유
    - 가장 관련 있는 포인트에 초점을 맞춘 맞춤 이력서 스냅샷
    - 회사, 제품, 가치의 간결한 요약
    - 직무와 회사에 기반한 예상 면접 질문
    - 인터뷰어에게 할 맞춤 질문
    - 톤, 집중 영역, 유의해야 할 레드 플래그에 대한 조언

    문서는 깔끔하고 명확하며, 후보자가 면접에서 전략적 우위를 갖도록 설계되어야 합니다.

    문서가 너무 짧지 않도록, 충분한 분량과 시간을 들여 포괄적으로 작성하세요.
  expected_output: >
    다음 섹션을 포함한 제목 "Interview Prep: $CompanyName – $JobTitle"의 Markdown 문서:
    - ## 직무 개요
    - ## 이 직무가 맞는 이유
    - ## 이 역할을 위한 이력서 하이라이트
    - ## 회사 요약
    - ## 예상 면접 질문
    - ## 그들에게 할 질문
    - ## 알아둘/복습할 개념
    - ## 전략적 조언

  agent: interview_prep_agent
  output_file: output/interview_prep.md