translate_task:
    description: >
        Translate {sentence} from English to Korean without making mistakes
    expected_output: >
        A well formatted translation from English to Korean using proper capitalization of names and places.
    agent: translator_agent

retranslate_task:
    description: >
        Translate {sentence} from Korean to French without making mistakes
    expected_output: >
        A well formatted translation from Korean to French using proper capitalization of names and places.
    agent: translator_agent

count_task:
    description: >
        Count the number of letters in sentence
    expected_output: >
        The number of letters in sentence.
    agent: counter_agent